import { Fragment } from 'react'
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';

import { LoginForm } from '@/components/login-form';

const inter = Inter({subsets: ['latin']});

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Auth with Next.js ☺</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <h1>Auth with Next.js</h1>
        <LoginForm/>
      </main>
    </Fragment>
  )
}
