import Head from 'next/head';
import { Fragment } from 'react'
import { Inter } from 'next/font/google';
import { Col, Row } from 'antd';

import { LoginForm } from '@/components/login-form';

const inter = Inter({subsets: ['latin']});

export default function Login() {

  return (
    <Fragment>
      <Head>
        <title>Auth with Next.js ☺</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <Row style={{ maxWidth: 600 }} justify="end" align="bottom">
          <Col span={24}>
            <h1>Auth with Next.js</h1>
            <LoginForm/>
          </Col>
        </Row>
      </main>
    </Fragment>
  )
}
